# Generated by Django 4.2.1 on 2023-06-08 13:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_slide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('f2a0967e-6431-47c4-8720-04c7a116259d'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(max_length=100000)),
                ('price', models.IntegerField(default=0)),
                ('offer_price', models.IntegerField(default=0)),
                ('delivery_charge', models.IntegerField(default=0)),
                ('star_5', models.IntegerField(default=0)),
                ('star_4', models.IntegerField(default=0)),
                ('star_3', models.IntegerField(default=0)),
                ('star_2', models.IntegerField(default=0)),
                ('star_1', models.IntegerField(default=0)),
                ('cod', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_set', to='backend.category')),
            ],
        ),
    ]
