# Generated by Django 4.2.1 on 2023-06-08 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2712e48a-b23b-4c00-9aff-548e7906ceed'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('90483195-7838-4553-bd0c-856cb8199ed7'), editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options_set', to='backend.product')),
            ],
        ),
    ]
