# Generated by Django 4.2.1 on 2023-06-08 14:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_product_id_alter_productoption_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('672d2714-72a0-484f-8fe0-8ad37edfe158'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productoption',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0b5b4557-e256-4354-b9e5-d33b68e04e49'), primary_key=True, serialize=False),
        ),
    ]
