# Generated by Django 4.2.1 on 2023-06-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_alter_product_id_alter_productoption_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='product/')),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_set', to='backend.productoption')),
            ],
        ),
    ]
