# Generated by Django 4.2.1 on 2023-06-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_pageitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageitem',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='pageitem',
            name='product_options',
            field=models.ManyToManyField(blank=True, to='backend.productoption'),
        ),
    ]
