# Generated by Django 4.2.2 on 2023-06-16 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_user_cart_user_wishlist_alter_pageitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
