# Generated by Django 4.2.2 on 2023-06-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_order_orderedproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pending_orders',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_set', to='backend.category'),
        ),
    ]
